//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курс
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarif
    {
        public int ID_tar { get; set; }
        public Nullable<System.DateTime> Date_yst { get; set; }
        public Nullable<double> Price_per_km { get; set; }
    }
}
