//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курс
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazi
    {
        public int ID { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<int> ID_dis { get; set; }
        public Nullable<int> ID_kli { get; set; }
        public Nullable<int> ID_car { get; set; }
        public Nullable<int> ID_dri { get; set; }
        public Nullable<int> ID_zaya { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Data_prin_zak { get; set; }
        public Nullable<double> Sum { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Dispetsher Dispetsher { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Klient Klient { get; set; }
        public virtual Statys Statys { get; set; }
        public virtual Zayavka Zayavka { get; set; }
    }
}
